### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells.

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [1]:
# YOUR CODE HERE
num = list(range(60,70))
print(num)
# raise NotImplementedError()

[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [5]:
# YOUR CODE HERE
import math

sum_of_numbers = 0
sum_of_squares = 0
i = 0  # Rename 'count' to 'i'

while True:
    number = float(input("Enter a number (or 0 to exit): "))
    if number == 0:
        break
    sum_of_numbers += number
    sum_of_squares += number ** 2
    i += 1  # Rename 'count' to 'i'

mean = sum_of_numbers / i if i > 0 else 0  # Rename 'count' to 'i'

if i > 1:
    variance = (sum_of_squares - (sum_of_numbers ** 2 / i)) / (i - 1)  # Rename 'count' to 'i'
    standard_deviation = math.sqrt(variance)
else:
    standard_deviation = 0

print("\nThe Mean is: " + str(round(mean, 4)) + "\n")  # Modified to round 'mean' properly
print("The Standard Deviation is: " + str(round(standard_deviation, 4)))  # Modified to round 'standard_deviation' properly


# raise NotImplementedError()

Enter a number (or 0 to exit): 4
Enter a number (or 0 to exit): 7
Enter a number (or 0 to exit): 9
Enter a number (or 0 to exit): 0

The Mean is: 6.6667

The Standard Deviation is: 2.5166


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [7]:
# YOUR CODE HERE
l = [2, 3, -2, -7, 0, 2, 3]
for num in l:
    if num %2 != 0:
        output = num
        print(output)
# raise NotImplementedError()

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [10]:
# YOUR CODE HERE
def get_n_primes(N):
    prime_numbers = []
    num = 2

    while len(prime_numbers) < N:
        if all(num % p != 0 for p in prime_numbers):
            prime_numbers.append(num)
        num += 1

    return prime_numbers

# raise NotImplementedError()

In [11]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [16]:
# YOUR CODE HERE

def get_nth_fibonacci(N):
    if N < 0:
        raise ValueError("N must be a non-negative integer")
    elif N == 0:
        return 0
    elif N == 1:
        return 1
    else:
        return get_nth_fibonacci(N - 1) + get_nth_fibonacci(N - 2)

# raise NotImplementedError()

In [17]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [20]:
# YOUR CODE HERE
def is_odd(N):
    return N %2 != 0

def is_prime(N):
    if(N==1 or N==0):
      return False
    for i in range(2,N):
        if(N%i==0):
            return False
    return True

def filter_list(new_list, condition):
    filtered_list = []
    for i in new_list:
        if condition(i):
            filtered_list.append(i)
    return filtered_list

# raise NotImplementedError()

In [21]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [22]:
# YOUR CODE HERE
def reduce(sequence, binary_function, initial_value=None):
    if initial_value is None:
        if len(sequence) == 0:
            raise ValueError("empty sequence with no initial value")
        accumulator = sequence[0]
        sequence = sequence[1:]
    else:
        accumulator = initial_value

    for item in sequence:
        accumulator = binary_function(accumulator, item)

    return accumulator

def add(x, y):
    return x + y

def string_len_add(x, y):
    return x + len(y)

# raise NotImplementedError()

In [23]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [28]:
# YOUR CODE HERE

# part (a)
# Creating binary function to count odd numbers
def count_odd(accumulator, item):
    if item % 2 != 0:
        return accumulator + 1
    return accumulator

# Using my reduce to count odd numbers
odd_count = reduce(l1, count_odd, 0)
print("Number of odd numbers:", odd_count)

# raise NotImplementedError()

Number of odd numbers: 3


In [29]:
# YOUR CODE HERE
# part b

# creating a binary function to find the maximum
def find_max(accumulator, item):
    return max(accumulator, item)

# Using my reduce to find the maximum
maximum = reduce(l1, find_max)
print("Maximum number:", maximum)

# raise NotImplementedError()

Maximum number: 5


In [30]:
# YOUR CODE HERE
# part c

# Creating a binary function to find the longest string
def find_longest(accumulator, item):
    return item if len(item) > len(accumulator) else accumulator

# Use my reduce to find the longest string
longest_string = reduce(l2, find_longest)
print("Longest string:", longest_string)

# raise NotImplementedError()


Longest string: hello


9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [32]:
# YOUR CODE HERE
import math

def pairwise_row_distance(matrix):
    N = len(matrix)
    M = len(matrix[0]) if N > 0 else 0

    D = [[0.0] * N for _ in range(N)]

    for i in range(N):
        for j in range(i, N):
            if i == j:
                D[i][j] = 0.0
            else:
                distance = math.sqrt(sum((matrix[i][k] - matrix[j][k]) ** 2 for k in range(M)))
                D[i][j] = distance
                D[j][i] = distance

    return D

def is_matrix(matrix):
    if not matrix:
        return False
    num_cols = len(matrix[0])
    return all(len(row) == num_cols for row in matrix)

def transpose(matrix):
    return [list(row) for row in zip(*matrix)]

#raise NotImplementedError()

In [33]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [34]:
# YOUR CODE HERE
class A:
    def __init__(self, value):
        self.value = value

    def print_value(self):
        print("Value:", self.value)
# raise NotImplementedError()

In [35]:
a = A("abc")
a.print_value()

Value: abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [40]:
# YOUR CODE HERE
class B:
    def __init__(self, public_param, private_param):
        self.this_is_public = public_param
        self.__this_is_private = private_param

# raise NotImplementedError()

In [41]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [42]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [43]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [45]:
# YOUR CODE HERE
class Animal:
    def __init__(self, name, age=0, fur_color=None):
        self.name = name
        self.age = age
        self.fur_color = fur_color
        self.number_of_legs = None

    def make_sound(self):
        pass  # This will be overridden by subclasses


class Cat(Animal):
    def __init__(self, name, age=0, fur_color=""):
        if isinstance(fur_color, (list, tuple)):
            fur_color = ', '.join(fur_color)
        super().__init__(name, age, fur_color)

    def make_sound(self):
        print("Meow!")


class Dog(Animal):
    def __init__(self, name, age=0, fur_color=()):
        if isinstance(fur_color, (list, tuple)):
            fur_color = ', '.join(fur_color)
        super().__init__(name, age, fur_color)

    def make_sound(self):
        print("Woof!")


class Fish(Animal):
    def __init__(self, name, age=0):
        super().__init__(name, age)

    def make_sound(self):
        print("Blub blub!")


class Eagle(Animal):
    def __init__(self, name, age=0):
        super().__init__(name, age)

    def make_sound(self):
        print("Screech!")


#raise NotImplementedError()

In [46]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

Could not initialize an animal: Cat.__init__() got an unexpected keyword argument 'fur'


#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [52]:
import numpy as np

In [53]:
def standardize(X):
      # YOUR CODE HERE
    col_means = np.mean(X, axis=0)
    col_stds = np.std(X, axis=0)
    X_std = (X - col_means) / col_stds
    X_std = np.round(X_std, 4)
    return X_std

    #raise NotImplementedError()

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-0.7071, -0.7071],
       [ 1.4142,  1.4142],
       [-0.7071, -0.7071]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [54]:
def normalize(X):
    # YOUR CODE HERE
    col_min = np.min(X, axis=0)
    col_max = np.max(X, axis=0)
    X_norm = (X - col_min) / (col_max - col_min)
    return X_norm
    #raise NotImplementedError()

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [55]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)